version: "3.8"

services:
    gymserver:
        build: .
        container_name: gym-app-server
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - ALLOWED_HOSTS=127.0.0.1
        ports:
            - "8000:8000"
        depends_on:
            - gymappdb
    gymappdb:
        image: postgres
        container_name: gymappdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
volumes:
    pgdata: