# Generated by Django 3.2.4 on 2021-06-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_product_shop'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.shop'),
        ),
    ]
