# Generated by Django 3.2.4 on 2021-06-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=5)),
                ('finish_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.gymmember')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.trainer')),
                ('working', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gym.workinghours')),
            ],
        ),
    ]
