# Generated by Django 3.2.4 on 2021-06-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('gym', '0002_alter_trainerhours_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerhours',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.gymmember'),
        ),
    ]
