# Generated by Django 3.2.4 on 2021-06-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptraining',
            name='training_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
